name: GitHub Actions Demo
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build library
        run: npm run build
      - name: Test library
        run: npm run test -- --watch=false --browsers=ChromeHeadless
