name: Make Candidate 
on:
  push:
    branches: [test/master]
    # paths:
    #   - '.github/workflows/**'
    #   - 'projects/core/**'
    #   - 'projects/integration/**'
    #   - 'docs/npm/**'
    #   - package.json
    #   - package-lock.json
    #   - angular.json
    #   - tsconfig.json
jobs:
  validate:
    uses: ./.github/workflows/testing.yml
    with:
      ref: ${{github.ref}}
      base_ref: test/stable
  stable:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test/stable
      - name: Merge into stable branch
        run: |
          git fetch --unshallow
          git merge origin/test/master
          git push