name: Make Candidate 
on:
  push:
    branches: [test/master]
    paths:
      - '.github/workflows/**'
      - 'projects/core/**'
      - 'projects/integration/**'
      - 'docs/npm/**'
      - package.json
jobs:
  validate:
    uses: ./.github/workflows/testing.yml
    with:
      ref: ${{github.ref}}
  stable:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - run: echo make candidate