name: Make Candidate 
on:
  push:
    branches: [test/master]
    paths:
      - 'projects/core/**'
      - 'projects/integration/**'
      - 'package.json'
      - 'package-lock.json'
      - 'angular.json'
      - 'tsconfig.json'
      - 'docs/npm/**'
jobs:
  validate:
    uses: ./.github/workflows/testing.yml
    with:
      ref: ${{github.ref}}
  stable:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - run: echo make candidate