name: Make Candidate 
on:
  push:
    branches: [master]
jobs:
  validate:
    uses: ./.github/workflows/testing.yml
    with:
      ref: ${{github.ref}}
      base_ref: origin/stable
  stable:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: stable
          fetch-depth: 0
      - name: Merge into stable branch
        run: |
          git merge origin/master
          git push