name: Test Code
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
jobs:
  pretest:
    runs-on: ubuntu-latest
    env:
      VALIDATED_PATHS: |
        .github/workflows,
        projects/core,
        projects/integration,
        docs/npm,
        package.json,
        package-lock.json,
        angular.json,
        tsconfig.json
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{inputs.ref}}
      - run: |
          git diff --name-only > _diff.txt
          echo $VALIDATED_PATHS | tr ',' '\n' | sed 's/\//\\\//g' | sed 's/\(.*\)/s\/^\1\/:::\//' > _patterns.sed
          N_FILES=$(sed -f _patterns.sed _diff.txt | grep ':::' | wc -l)
          HAS_FILES=$([ "$N_FILES" -eq "0" ] && echo false || echo true)
          echo "::set-output name=has::$($HAS_FILES)"
  test:
    needs: pretest
    # if: ${{ needs.pretest.outputs.has == 'true' }}
    if: ${{ needs.pretest.outputs.has != null }}
    runs-on: ubuntu-latest
    steps:
      - run: echo does nothing
# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Setup Chrome
#         uses: browser-actions/setup-chrome@latest
#         with:
#           chrome-version: stable
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{inputs.ref}}
#       - name: Setup node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '12.x'
#           cache: 'npm'
#       - name: Install dependencies
#         run: npm ci
#       - name: Build library
#         run: npm run build
#       - name: Test library
#         run: npm run test -- --watch=false --browsers=ChromeHeadless
#   integration-tests:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         environment:
#           - angular-v7
#           - angular-v8
#           - angular-v9
#           - angular-v10
#           - angular-v11
#           - angular-v12
#           - angular-v13
#     steps:
#       - name: Setup Chrome
#         uses: browser-actions/setup-chrome@latest
#         with:
#           chrome-version: stable
#       - name: Checkout angular-wform
#         uses: actions/checkout@v2
#         with:
#           path: angular-wform
#           ref: ${{inputs.ref}}
#       - name: Checkout angular-wform-integration
#         uses: actions/checkout@v2
#         with:
#           repository: iexela/angular-wform-integration
#           path: angular-wform-integration
#       - name: Setup node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '12.x'
#           cache: 'npm'
#           cache-dependency-path: '**/package-lock.json'
#       - name: Build integration library
#         run: |
#           cd angular-wform
#           npm ci
#           npm run build:integration
#       - name: Run integration tests
#         run: |
#           cd angular-wform-integration
#           npm ci
#           npm test ${{matrix.environment}} $GITHUB_WORKSPACE/angular-wform/dist/integration
